### ISSUE TITLE
Create add_species() function

### ISSUE THREAD

**Issue by gustavdelius** [gustavdelius/mizer#20]
Create a function that takes an existing params object and adds another species to it. This will be a wrapper for the code that implements #17, thus this task should be done after completion of #17.

**Comment by richardsouthwell** [comment]
Having an add species function will be extremely useful.

**Comment by richardsouthwell** [comment]
however, one has to specify more info to add a species to a mizer params object than the amount of info you have to specify if you use mizer to fill out the parameter values.

**Comment by richardsouthwell** [comment]
Maybe we might also want to extend the maximum weight involved in the size grid when add_species() is used to include something larger

**Comment by gustavdelius** [comment]
I think add_species should only allow the addition of a species that sits well inside the size-ranges of the background species. There should always be background species smaller and larger than the foreground species.

**Comment by richardsouthwell** [comment]
So here is the proposed approach:

Look at original system, and determine the growth rates and death rates that would be experienced by the new species, neglecting self interaction. 1

Determine the MvF steady state associated with these growth and death rates, and rescale it by an preset abundance multiplier. 

Determine the modified growth and death rates experienced by the pre-existing species due to the addition of the new species, and use these to determine new steady state abundance curves for the pre-existing species.

Manipulate the abundance multipliers to get pow law again.

For different abundance multipliers of pre-existing species try,  determine the MvF steady states of the pre-existing species in the new system,

**Comment by gustavdelius** [comment]
I am not sure that we want to do your step 3 before your step 4 because the growth and death rates we get before the abundance multipliers are adjusted are rather artificial.

Also I think you forgot to put in the step of adjusting the parameters to achieve coexistence.

Here is how I see the proposed approach:

1. Calculate the solution for the new species with the provided parameters and with the death and growth rates calculated from the existing system.

2. Adjust erepro for the new species so that (F-1)/F RDI = RDD (where F = R_max/RDD). If this can be achieved by just adjusting erepro, go to step 3. Otherwise go back to step 1 with the adjusted parameters.

3. Change abundance multipliers of background species to get the community spectrum back to close to a power law.

4. At this stage death rates will have been changed for some species, so recalculate the solutions for all species, one-by-one.

5. Readjust all erepros

Of course we could iterate various steps to get better results, but I think for now that will not be necessary.

I think the code for solving the linear equation for a species in a given community should go into a function solve_linear(species, params) because it will be used several times: once in step 1 and once for each species in step 4. I'll put it in a separate issue.

**Comment by richardsouthwell** [comment]
We just decided to skip step 2 for the moment.

**Comment by richardsouthwell** [comment]
My plan is to write add_species(params,sp_params) that extracts the necessary species params, and from sp_params (for the new species), 
these are combined into a new mizer params object has theta on, except theta (new_sp,new_sp)=0 .
We use this params object and solve the MvF for the new_sp (via getZ, getEgrowth etc.) and use the solution to fill params@initial_n with abundance_multiplier=1, for the new species. We then turn the theta matrix to be full of 1s, and output the resulting params object. 
and return it.

**Comment by richardsouthwell** [comment]
A feature that our add species function should have that: if we add in another species identical one of the pre-existing ones then the output state should basically look the same, just with the abundance shared between the pre-existing species and the newly added copy.
