### ISSUE TITLE
Collect parameters for red mullet and hake

### ISSUE THREAD

**Issue by gustavdelius** [gustavdelius/mizer#29]
Collect parameters, together with sources and justifications.

**Comment by richardsouthwell** [comment]
Some red mullet data at 
http://www.fishbase.org/Summary/SpeciesSummary.php?ID=790&AT=red+mullet
Including weight/length conversion parameters a & b.
At
http://www.fishbase.org/popdyn/PopGrowthList.php?ID=790&GenusName=Mullus&SpeciesName=barbatus+barbatus&fc=332
there is data on L_inf, and k_vb
