### ISSUE TITLE
Allow arbitrary feeding kernel

### ISSUE THREAD

**Issue by gustavdelius** [gustavdelius/mizer#84]
I propose that we allow another column in the species params data frame that holds the name of the function that calculates the feeding kernel for that species. By default this will be set to "phi" and the function phi will calculate the standard log-normal kernel cut off at 1 and beta exp(3 sigma). Thus this mechanism for specifying alternative feeding kernels would be exactly the same as that used currently for specifying fishing gears. Besides the column for the function name we also would need a column for the lower cutoff (which will be set to beta exp(3 sigma) by default) because we need to know that cutoff when setting up the fourier transform. I propose that we leave the upper cutoff at 1 (meaning that predators do not feed on prey larger than themselves) or otherwise we need to take a look at the FFT scheme for the mortality integral to see if it needs modification.

**Comment by gustavdelius** [comment]
Hi @astaaudzi , the current proposal is just to allow alternative forms of the feeding kernel that depends only on the predator species and on the predator/prey size ratio. Such a feeding kernel does of course lead to changes in the range of suitable prey as the predator grows. Keeping the same prey size range as the predator grows would be a very different and very fundamental change.

**Comment by astaaudzi** [comment]
OK, makes sense. I agree that allowing changing PPMR with size would be a fundamental change and a deviation from the size spectrum model philosophy :)
