### ISSUE TITLE
Rename functions for consistency and expressiveness

### ISSUE THREAD

**Issue by gustavdelius** [gustavdelius/mizer#89]
We will introduce new names for some functions but keep the old names around as aliases. Introducing aliases is very easy in R. For example
```
#' Alias for getAvailEnergy
#' 
#' #' An alias provided for backward compatibility with mizer version <= 1.0
#' @inherit getAvailEnergy
getPhiPrey <- getAvailEnergy
```
Here are the aliases I have started to introduce. The name on the right is the new one.
```
MizerParams <- multispeciesParams
getPhiPrey <- getAvailEnergy
getM2 <- getPredMort
getM2Background <- getPlanktonPredMort
getZ <- getMort
getESpawning<- getERepro  # To be consistent with getEReproAndGrowth
```
Until our next release we can come up with better names. So all suggestions welcome @richardsouthwell .

**Comment by richardsouthwell** [comment]
I like it all, except I might call it getPlanktonMort, as I dont think we allow anything but predation-type mortality on the plankton
