### ISSUE TITLE
Update calculation of default gamma to take into account resources

### ISSUE THREAD

**Issue by gustavdelius** [gustavdelius/mizer#93]
Currently, if gamma is not provided in species params, it is set so that an individual feeding on power-law plankton has the desired feeding level f_0. This should be updated so that a individual feeding on plankton and resources according to the parameters interaction_p, rho and B has the desired feeding level.

**Comment by astaaudzi** [comment]
I am not sure I understand what this means. What are the _p and B parameters?

**Comment by gustavdelius** [comment]
Hi @astaaudzi , the issues on my own repository are often written so they make sense only to me. Any issues that are of interests to others I will post on sizespectrum/mizer. You can unwatch my repository in order not to get notifications.

**Comment by astaaudzi** [comment]
:) 
Ok, I won't comment and ask silly questions, but it is still interesting to see what developments might be happening

**Comment by gustavdelius** [comment]
This is taken care of in core mizer's new extension mechanism.
